include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    use_super_parameters: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    constant_identifier_names: ignore
