-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.
--
-- Eminence HRIS (Digital 201) - PostgreSQL data schema, schema `public`.
-- Derived from backend/prisma/schema.prisma and backend/prisma/migrations
-- (baseline through 20261004140606_privacy_consent). 24 tables, 15 enum types.
-- To change the database, write a Prisma migration; do not edit this file instead.

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS citext;  -- case-insensitive email and station names

-- ---------------------------------------------------------------------------
-- Enum types
-- ---------------------------------------------------------------------------
CREATE TYPE public."UserRole" AS ENUM (
  'SYSTEM_ADMIN', 'AO_II', 'HRMO', 'TEACHING_PERSONNEL', 'NON_TEACHING_PERSONNEL',
  'RECORDS_PERSONNEL'  -- retired; no account holds it, removal needs an enum rebuild
);
CREATE TYPE public."AccountStatus"        AS ENUM ('PENDING', 'ACTIVE', 'LOCKED', 'INACTIVE');
CREATE TYPE public."AccountRequestStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE public."Gender"               AS ENUM ('MALE', 'FEMALE', 'OTHER');
CREATE TYPE public."CivilStatus"          AS ENUM ('SINGLE', 'MARRIED', 'WIDOWED', 'SEPARATED');
CREATE TYPE public."PersonnelStatus"      AS ENUM ('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'RETIRED', 'ARCHIVED');
CREATE TYPE public."AppointmentStatus"    AS ENUM (
  'PERMANENT', 'PROVISIONAL', 'TEMPORARY', 'SUBSTITUTE', 'CASUAL', 'CONTRACTUAL', 'COTERMINOUS'
);
-- Workflow: DRAFT -> PENDING_VALIDATION (AO II) -> FOR_APPROVAL (HRMO) -> APPROVED,
-- with DEFICIENCY, REJECTED and ABANDONED. ESCALATED, COMPLETED, ARCHIVED are reserved.
CREATE TYPE public."TransactionStatus" AS ENUM (
  'DRAFT', 'PENDING_VALIDATION', 'FOR_APPROVAL', 'APPROVED', 'REJECTED',
  'DEFICIENCY', 'ESCALATED', 'ABANDONED', 'COMPLETED', 'ARCHIVED'
);
CREATE TYPE public."DocumentStatus" AS ENUM (
  'PENDING_UPLOAD', 'PENDING_OCR', 'OCR_PROCESSED', 'OCR_REVIEWED',
  'VALIDATED', 'REJECTED', 'REQUIRES_MANUAL_REVIEW'
);
CREATE TYPE public."PersonnelDocumentStatus" AS ENUM (
  'NOT_SUBMITTED', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'REPLACEMENT_REQUIRED'
);
CREATE TYPE public."PromotionCycleType"   AS ENUM ('RECLASSIFICATION', 'NATURAL_VACANCY', 'ECP');
CREATE TYPE public."PromotionCycleStatus" AS ENUM (
  'PLANNING', 'CONFIGURED', 'ACTIVE', 'CLOSED', 'RESULTS_READY', 'PUBLISHED', 'FINALIZED',
  'EVALUATION', 'COMPARATIVE_ASSESSMENT', 'RESOLVED', 'CANCELLED'
);
CREATE TYPE public."PromotionApplicationStatus" AS ENUM (
  'SUBMITTED', 'UNDER_REVIEW', 'RANKED', 'APPROVED', 'REJECTED'
);
CREATE TYPE public."CareerEventType" AS ENUM (
  'PROMOTION', 'TRAINING', 'AWARD', 'DESIGNATION_CHANGE', 'RECLASSIFICATION', 'OTHER'
);
CREATE TYPE public."NotificationType" AS ENUM ('INFO', 'WARNING', 'SUCCESS', 'ERROR');

-- ---------------------------------------------------------------------------
-- Tables (alphabetical)
-- Every timestamp is timestamp(3) without time zone, stored in UTC by Prisma.
-- Columns named updated_at are set by Prisma on every write (no database default).
-- ---------------------------------------------------------------------------

-- A request (usually from an AO II) for the System Administrator to create an account.
CREATE TABLE public.account_creation_requests (
  id                      integer NOT NULL DEFAULT nextval('account_creation_requests_id_seq'::regclass),
  requested_by_user_id    integer NOT NULL,
  first_name              text NOT NULL,
  last_name               text NOT NULL,
  middle_name             text,
  suffix                  text,
  email                   citext NOT NULL,
  birth_date              timestamp(3) without time zone,
  gender                  public."Gender",
  civil_status            public."CivilStatus",
  contact_number          text,
  address                 text,
  role                    public."UserRole" NOT NULL,
  designation             text NOT NULL,
  school                  text,
  district                text,
  initial_password        text NOT NULL,
  date_hired              timestamp(3) without time zone,
  pds_original_file_name  text,
  pds_storage_path        text,
  pds_mime_type           text,
  pds_file_size           integer,
  status                  public."AccountRequestStatus" NOT NULL DEFAULT 'PENDING',
  rejection_reason        text,
  created_user_id         integer,
  created_at              timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at              timestamp(3) without time zone NOT NULL,
  CONSTRAINT account_creation_requests_pkey PRIMARY KEY (id),
  CONSTRAINT account_creation_requests_requested_by_user_id_fkey FOREIGN KEY (requested_by_user_id)
    REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT account_creation_requests_created_user_id_fkey FOREIGN KEY (created_user_id)
    REFERENCES public.users(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- One backup or restore-drill result, reported by the job itself.
CREATE TABLE public.backup_runs (
  id                 integer NOT NULL DEFAULT nextval('backup_runs_id_seq'::regclass),
  run_key            text NOT NULL,             -- makes a re-sent report idempotent
  kind               text NOT NULL,             -- DATABASE_BACKUP | RESTORE_DRILL
  status             text NOT NULL,             -- SUCCEEDED | FAILED
  started_at         timestamp(3) without time zone,
  finished_at        timestamp(3) without time zone,
  size_bytes         bigint,
  encrypted          boolean,
  manifest_verified  boolean,
  missing_objects    integer,
  object_count       integer,
  retention_days     integer,
  error              text,
  source             text,
  reported_at        timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT backup_runs_pkey PRIMARY KEY (id),
  CONSTRAINT backup_runs_run_key_key UNIQUE (run_key)
);

CREATE TABLE public.career_history_entries (
  id            integer NOT NULL DEFAULT nextval('career_history_entries_id_seq'::regclass),
  personnel_id  integer NOT NULL,
  event_type    public."CareerEventType" NOT NULL,
  event_date    timestamp(3) without time zone NOT NULL,
  details_json  jsonb,
  document_id   integer,
  created_at    timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    timestamp(3) without time zone NOT NULL,
  CONSTRAINT career_history_entries_pkey PRIMARY KEY (id),
  CONSTRAINT career_history_entries_document_id_key UNIQUE (document_id),
  CONSTRAINT career_history_entries_personnel_id_fkey FOREIGN KEY (personnel_id)
    REFERENCES public.personnel(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT career_history_entries_document_id_fkey FOREIGN KEY (document_id)
    REFERENCES public.uploaded_documents(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Immutable snapshots of an uploaded transaction document. id is a UUID set by the app.
CREATE TABLE public.document_revisions (
  id           text NOT NULL,
  document_id  integer NOT NULL,
  snapshot     jsonb NOT NULL,
  created_at   timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT document_revisions_pkey PRIMARY KEY (id),
  CONSTRAINT document_revisions_document_id_fkey FOREIGN KEY (document_id)
    REFERENCES public.uploaded_documents(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Saved, unfinished form (e.g. PDS) for a transaction; one per template.
CREATE TABLE public.form_drafts (
  transaction_id  integer NOT NULL,
  template_id     text NOT NULL,
  version         text NOT NULL,
  payload         jsonb NOT NULL,
  updated_at      timestamp(3) without time zone NOT NULL,
  CONSTRAINT form_drafts_pkey PRIMARY KEY (transaction_id, template_id),
  CONSTRAINT form_drafts_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES public.transactions(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- One pending "is this you?" sign-in from a new device: a hashed 6-digit code.
CREATE TABLE public.login_challenges (
  id            integer NOT NULL DEFAULT nextval('login_challenges_id_seq'::regclass),
  user_id       integer NOT NULL,
  token_hash    text NOT NULL,
  code_hash     text NOT NULL,
  label         text NOT NULL,
  ip_address    text,
  attempts      integer NOT NULL DEFAULT 0,
  last_sent_at  timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at    timestamp(3) without time zone NOT NULL,
  consumed_at   timestamp(3) without time zone,
  created_at    timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT login_challenges_pkey PRIMARY KEY (id),
  CONSTRAINT login_challenges_token_hash_key UNIQUE (token_hash),
  CONSTRAINT login_challenges_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE public.notifications (
  id                   integer NOT NULL DEFAULT nextval('notifications_id_seq'::regclass),
  user_id              integer NOT NULL,
  message              text NOT NULL,
  type                 public."NotificationType" NOT NULL,
  is_read              boolean NOT NULL DEFAULT false,
  created_at           timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  related_entity_id    integer,
  related_entity_type  text,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- The personnel record (Digital 201 profile). Exactly one per user account.
CREATE TABLE public.personnel (
  id                  integer NOT NULL DEFAULT nextval('personnel_id_seq'::regclass),
  user_id             integer NOT NULL,
  employee_id         text NOT NULL,
  first_name          text NOT NULL,
  last_name           text NOT NULL,
  middle_name         text,
  suffix              text,
  birth_date          timestamp(3) without time zone,
  gender              public."Gender",
  civil_status        public."CivilStatus",
  contact_number      text,
  address             text,
  school              citext,   -- station; AO II scope is resolved from this column only
  district            citext,
  designation         text NOT NULL,
  date_hired          timestamp(3) without time zone,
  appointment_status  public."AppointmentStatus",  -- null = not on file
  status              public."PersonnelStatus" NOT NULL,
  plantilla_item_id   integer,
  profile_complete    boolean NOT NULL DEFAULT false,
  created_at          timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          timestamp(3) without time zone NOT NULL,
  CONSTRAINT personnel_pkey PRIMARY KEY (id),
  CONSTRAINT personnel_user_id_key UNIQUE (user_id),
  CONSTRAINT personnel_employee_id_key UNIQUE (employee_id),
  CONSTRAINT personnel_plantilla_item_id_key UNIQUE (plantilla_item_id),
  CONSTRAINT personnel_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT personnel_plantilla_item_id_fkey FOREIGN KEY (plantilla_item_id)
    REFERENCES public.plantilla_items(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- A document in a person's Digital 201 file. A replacement is a new row that
-- points at the one it supersedes; rows are soft-deleted via deleted_at.
CREATE TABLE public.personnel_files (
  id                       integer NOT NULL DEFAULT nextval('personnel_files_id_seq'::regclass),
  personnel_id             integer NOT NULL,
  document_type_id         text NOT NULL,
  document_type_name       text NOT NULL,
  original_file_name       text,
  stored_file_name         text,
  storage_path             text,
  mime_type                text,
  file_size                integer,
  is_required              boolean NOT NULL DEFAULT true,
  issue_date               date,
  expiration_date          date,
  remarks                  text,
  status                   public."PersonnelDocumentStatus" NOT NULL DEFAULT 'NOT_SUBMITTED',
  rejection_reason         text,
  reviewed_at              timestamp(3) without time zone,
  reviewed_by_user_id      integer,
  replaces_document_id     integer,
  ocr_extracted_data_json  jsonb,
  ocr_confidence_score     double precision,
  ocr_status               text,
  ocr_processed_at         timestamp(3) without time zone,
  ocr_error_message        text,
  deleted_at               timestamp(3) without time zone,
  created_at               timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at               timestamp(3) without time zone NOT NULL,
  CONSTRAINT personnel_files_pkey PRIMARY KEY (id),
  CONSTRAINT personnel_files_personnel_id_fkey FOREIGN KEY (personnel_id)
    REFERENCES public.personnel(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT personnel_files_reviewed_by_user_id_fkey FOREIGN KEY (reviewed_by_user_id)
    REFERENCES public.users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT personnel_files_replaces_document_id_fkey FOREIGN KEY (replaces_document_id)
    REFERENCES public.personnel_files(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- A plantilla (authorised position) item. It is occupied exactly when a
-- personnel row references it; there is no separate occupancy flag.
CREATE TABLE public.plantilla_items (
  id              integer NOT NULL DEFAULT nextval('plantilla_items_id_seq'::regclass),
  item_number     text NOT NULL,
  position_title  text NOT NULL,
  salary_grade    integer NOT NULL,
  department      text NOT NULL,
  division        text NOT NULL,
  created_at      timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      timestamp(3) without time zone NOT NULL,
  CONSTRAINT plantilla_items_pkey PRIMARY KEY (id),
  CONSTRAINT plantilla_items_item_number_key UNIQUE (item_number)
);

-- Evidence that a person accepted a version of the Privacy Notice.
CREATE TABLE public.privacy_consents (
  id              integer NOT NULL DEFAULT nextval('privacy_consents_id_seq'::regclass),
  user_id         integer NOT NULL,
  notice_version  text NOT NULL,
  accepted_at     timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip_address      text,
  user_agent      text,
  CONSTRAINT privacy_consents_pkey PRIMARY KEY (id),
  CONSTRAINT privacy_consents_user_id_notice_version_key UNIQUE (user_id, notice_version),
  CONSTRAINT privacy_consents_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE public.promotion_applications (
  id                  integer NOT NULL DEFAULT nextval('promotion_applications_id_seq'::regclass),
  applicant_number    text,
  personnel_id        integer NOT NULL,
  promotion_cycle_id  integer NOT NULL,
  status              public."PromotionApplicationStatus" NOT NULL,
  application_date    timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  final_rank          integer,
  score_details_json  jsonb,
  created_at          timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          timestamp(3) without time zone NOT NULL,
  CONSTRAINT promotion_applications_pkey PRIMARY KEY (id),
  CONSTRAINT promotion_applications_applicant_number_key UNIQUE (applicant_number),
  CONSTRAINT promotion_applications_personnel_id_promotion_cycle_id_key UNIQUE (personnel_id, promotion_cycle_id),
  CONSTRAINT promotion_applications_personnel_id_fkey FOREIGN KEY (personnel_id)
    REFERENCES public.personnel(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT promotion_applications_promotion_cycle_id_fkey FOREIGN KEY (promotion_cycle_id)
    REFERENCES public.promotion_cycles(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE public.promotion_cycles (
  id                        integer NOT NULL DEFAULT nextval('promotion_cycles_id_seq'::regclass),
  name                      text NOT NULL,
  type                      public."PromotionCycleType" NOT NULL,
  start_date                timestamp(3) without time zone NOT NULL,
  end_date                  timestamp(3) without time zone NOT NULL,
  status                    public."PromotionCycleStatus" NOT NULL,
  rules_configuration_json  jsonb,
  created_at                timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                timestamp(3) without time zone NOT NULL,
  CONSTRAINT promotion_cycles_pkey PRIMARY KEY (id)
);

-- token holds a SHA-256 hash of the refresh token, never the token itself.
CREATE TABLE public.refresh_tokens (
  id            integer NOT NULL DEFAULT nextval('refresh_tokens_id_seq'::regclass),
  token         text NOT NULL,
  client        text NOT NULL DEFAULT 'web',  -- 'web' sessions expire when idle; 'app' do not
  last_used_at  timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id       integer NOT NULL,
  expires_at    timestamp(3) without time zone NOT NULL,
  created_at    timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked       boolean NOT NULL DEFAULT false,
  CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT refresh_tokens_token_key UNIQUE (token),
  CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- A document a transaction type requires (e.g. PDS, appointment paper).
CREATE TABLE public.requirement_templates (
  id                   integer NOT NULL DEFAULT nextval('requirement_templates_id_seq'::regclass),
  transaction_type_id  integer NOT NULL,
  name                 text NOT NULL,
  description          text,
  is_mandatory         boolean NOT NULL DEFAULT true,
  expected_data_type   text NOT NULL,
  ocr_fields_json      jsonb,
  created_at           timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           timestamp(3) without time zone NOT NULL,
  CONSTRAINT requirement_templates_pkey PRIMARY KEY (id),
  CONSTRAINT requirement_templates_transaction_type_id_fkey FOREIGN KEY (transaction_type_id)
    REFERENCES public.transaction_types(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE public.roles (
  id           integer NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
  name         public."UserRole" NOT NULL,
  description  text,
  CONSTRAINT roles_pkey PRIMARY KEY (id),
  CONSTRAINT roles_name_key UNIQUE (name)
);

CREATE TABLE public.transaction_types (
  id           integer NOT NULL DEFAULT nextval('transaction_types_id_seq'::regclass),
  name         text NOT NULL,
  description  text,
  CONSTRAINT transaction_types_pkey PRIMARY KEY (id),
  CONSTRAINT transaction_types_name_key UNIQUE (name)
);

-- An HR transaction moving through validation (AO II) and approval (HRMO).
CREATE TABLE public.transactions (
  id                      integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass),
  personnel_id            integer NOT NULL,
  transaction_type_id     integer NOT NULL,
  status                  public."TransactionStatus" NOT NULL,
  submission_date         timestamp(3) without time zone,
  validation_date         timestamp(3) without time zone,
  approval_date           timestamp(3) without time zone,
  remarks                 text,
  current_assignee_id     integer,
  resubmission_count      integer NOT NULL DEFAULT 0,
  stage_entered_at        timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP,  -- queue wait starts here
  escalated_at            timestamp(3) without time zone,  -- repeated corrections sent it to HRMO (BR-27)
  escalation_reviewed_at  timestamp(3) without time zone,  -- HRMO returned it with instructions
  deficiency_deadline     timestamp(3) without time zone,
  created_at              timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at              timestamp(3) without time zone NOT NULL,
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_personnel_id_fkey FOREIGN KEY (personnel_id)
    REFERENCES public.personnel(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT transactions_transaction_type_id_fkey FOREIGN KEY (transaction_type_id)
    REFERENCES public.transaction_types(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT transactions_current_assignee_id_fkey FOREIGN KEY (current_assignee_id)
    REFERENCES public.users(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- A browser or phone that passed an emailed sign-in code (hash of the device token only).
CREATE TABLE public.trusted_devices (
  id            integer NOT NULL DEFAULT nextval('trusted_devices_id_seq'::regclass),
  user_id       integer NOT NULL,
  token_hash    text NOT NULL,
  label         text NOT NULL,
  ip_address    text,
  created_at    timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_used_at  timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at    timestamp(3) without time zone NOT NULL,
  revoked_at    timestamp(3) without time zone,
  CONSTRAINT trusted_devices_pkey PRIMARY KEY (id),
  CONSTRAINT trusted_devices_token_hash_key UNIQUE (token_hash),
  CONSTRAINT trusted_devices_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- A file submitted for one requirement of one transaction (one slot per pair).
CREATE TABLE public.uploaded_documents (
  id                       integer NOT NULL DEFAULT nextval('uploaded_documents_id_seq'::regclass),
  transaction_id           integer NOT NULL,
  requirement_template_id  integer NOT NULL,
  storage_path             text NOT NULL,
  file_name                text NOT NULL,
  file_size                integer,
  mime_type                text,
  file_hash                text,
  uploaded_by_user_id      integer NOT NULL,
  upload_date              timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status                   public."DocumentStatus" NOT NULL,
  ocr_extracted_data_json  jsonb,
  ocr_confidence_score     double precision,
  corrected_ocr_data_json  jsonb,
  validation_notes         text,
  validated_by_user_id     integer,
  validation_date          timestamp(3) without time zone,
  is_duplicate             boolean NOT NULL DEFAULT false,
  created_at               timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at               timestamp(3) without time zone NOT NULL,
  CONSTRAINT uploaded_documents_pkey PRIMARY KEY (id),
  CONSTRAINT uploaded_documents_transaction_id_requirement_template_id_key
    UNIQUE (transaction_id, requirement_template_id),
  CONSTRAINT uploaded_documents_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES public.transactions(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT uploaded_documents_requirement_template_id_fkey FOREIGN KEY (requirement_template_id)
    REFERENCES public.requirement_templates(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT uploaded_documents_uploaded_by_user_id_fkey FOREIGN KEY (uploaded_by_user_id)
    REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT uploaded_documents_validated_by_user_id_fkey FOREIGN KEY (validated_by_user_id)
    REFERENCES public.users(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- Single-use magic sign-in links already consumed (replay guard).
CREATE TABLE public.used_magic_tokens (
  id          integer NOT NULL DEFAULT nextval('used_magic_tokens_id_seq'::regclass),
  jti         text NOT NULL,
  user_id     integer NOT NULL,  -- no foreign key
  used_at     timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at  timestamp(3) without time zone NOT NULL,
  CONSTRAINT used_magic_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT used_magic_tokens_jti_key UNIQUE (jti)
);

CREATE TABLE public.users (
  id                     integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  email                  citext NOT NULL,  -- unique regardless of case
  password_hash          text NOT NULL,
  role_id                integer NOT NULL,
  account_status         public."AccountStatus" NOT NULL DEFAULT 'PENDING',
  created_at             timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at             timestamp(3) without time zone NOT NULL,
  last_login             timestamp(3) without time zone,
  failed_login_attempts  integer NOT NULL DEFAULT 0,
  must_change_password   boolean NOT NULL DEFAULT false,  -- set when an admin issues/resets a password
  locked_until           timestamp(3) without time zone,
  device_verification    boolean NOT NULL DEFAULT true,   -- new-device sign-in needs an emailed code
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_email_key UNIQUE (email),
  CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.roles(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Audit trail. Rows are hash-chained (record_hash / previous_hash).
CREATE TABLE public.validation_logs (
  id                integer NOT NULL DEFAULT nextval('validation_logs_id_seq'::regclass),
  entity_type       text NOT NULL,
  entity_id         integer NOT NULL,
  action            text NOT NULL,
  details_json      jsonb,
  user_id           integer NOT NULL,
  ip_address        text,
  user_agent        text,
  status            text NOT NULL DEFAULT 'SUCCESS',
  "timestamp"       timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  category          text,
  severity          text DEFAULT 'INFO',
  outcome           text DEFAULT 'SUCCESS',
  action_label      text,
  target_type       text,
  target_id         integer,
  target_reference  text,
  actor_email       text,
  actor_role        text,
  actor_station     text,
  client_source     text DEFAULT 'web',
  request_id        text,
  failure_reason    text,
  record_hash       text,
  previous_hash     text,
  hash_version      integer,
  CONSTRAINT validation_logs_pkey PRIMARY KEY (id),
  CONSTRAINT validation_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Transactional outbox for workflow side effects (emails, notifications). id is a UUID set by the app.
CREATE TABLE public.workflow_outbox (
  id            text NOT NULL,
  event_key     text NOT NULL,
  kind          text NOT NULL,
  payload       jsonb NOT NULL,
  attempts      integer NOT NULL DEFAULT 0,
  available_at  timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at  timestamp(3) without time zone,
  last_error    text,
  created_at    timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT workflow_outbox_pkey PRIMARY KEY (id),
  CONSTRAINT workflow_outbox_event_key_key UNIQUE (event_key)
);

-- ---------------------------------------------------------------------------
-- Secondary indexes
-- ---------------------------------------------------------------------------
CREATE INDEX backup_runs_kind_reported_at_idx               ON public.backup_runs (kind, reported_at);
CREATE INDEX document_revisions_document_id_idx             ON public.document_revisions (document_id);
CREATE INDEX login_challenges_user_id_idx                   ON public.login_challenges (user_id);
CREATE INDEX notifications_user_id_is_read_idx              ON public.notifications (user_id, is_read);
CREATE INDEX personnel_school_idx                           ON public.personnel (school);
CREATE INDEX personnel_district_idx                         ON public.personnel (district);
CREATE INDEX personnel_files_personnel_id_deleted_at_idx    ON public.personnel_files (personnel_id, deleted_at);
CREATE INDEX personnel_files_expiration_date_idx            ON public.personnel_files (expiration_date);
CREATE INDEX promotion_applications_promotion_cycle_id_idx  ON public.promotion_applications (promotion_cycle_id);
CREATE INDEX refresh_tokens_user_id_idx                     ON public.refresh_tokens (user_id);
CREATE INDEX transactions_personnel_id_idx                  ON public.transactions (personnel_id);
CREATE INDEX transactions_status_idx                        ON public.transactions (status);
CREATE INDEX transactions_status_stage_entered_at_idx       ON public.transactions (status, stage_entered_at);
CREATE INDEX trusted_devices_user_id_idx                    ON public.trusted_devices (user_id);
CREATE INDEX validation_logs_entity_type_entity_id_idx      ON public.validation_logs (entity_type, entity_id);
CREATE INDEX validation_logs_user_id_idx                    ON public.validation_logs (user_id);
CREATE INDEX validation_logs_timestamp_idx                  ON public.validation_logs ("timestamp");
CREATE INDEX validation_logs_category_idx                   ON public.validation_logs (category);
CREATE INDEX validation_logs_severity_idx                   ON public.validation_logs (severity);
CREATE INDEX validation_logs_outcome_idx                    ON public.validation_logs (outcome);
CREATE INDEX validation_logs_action_idx                     ON public.validation_logs (action);
CREATE INDEX validation_logs_request_id_idx                 ON public.validation_logs (request_id);
CREATE INDEX validation_logs_target_type_target_id_idx      ON public.validation_logs (target_type, target_id);

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

-- Trims and collapses whitespace in station names; empty becomes NULL.
CREATE OR REPLACE FUNCTION public.canonicalize_personnel_station() RETURNS trigger AS $$
BEGIN
  NEW.school   := NULLIF(btrim(regexp_replace(NEW.school,   '[ \t\n\r\f\v]+', ' ', 'g')), '');
  NEW.district := NULLIF(btrim(regexp_replace(NEW.district, '[ \t\n\r\f\v]+', ' ', 'g')), '');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER personnel_canonical_station
  BEFORE INSERT OR UPDATE OF school, district ON public.personnel
  FOR EACH ROW EXECUTE FUNCTION public.canonicalize_personnel_station();

-- Fills category, target_type/target_id, outcome and severity when an older
-- write site leaves them out. Full body: migration 202609280001_audit_trail_hardening.
CREATE TRIGGER validation_logs_canonical_defaults
  BEFORE INSERT ON public.validation_logs
  FOR EACH ROW EXECUTE FUNCTION public.validation_logs_fill_canonical_defaults();

-- ---------------------------------------------------------------------------
-- Relationship summary
-- ---------------------------------------------------------------------------
-- roles 1──* users 1──0..1 personnel *──0..1 plantilla_items (unique: one occupant per item)
-- users 1──* refresh_tokens | trusted_devices | login_challenges | privacy_consents | notifications | validation_logs
-- users 1──* account_creation_requests (requested_by_user_id, created_user_id)
-- personnel 1──* transactions *──1 transaction_types 1──* requirement_templates
-- transactions 1──* uploaded_documents *──1 requirement_templates
-- transactions 1──* form_drafts
-- uploaded_documents 1──* document_revisions
-- uploaded_documents 1──0..1 career_history_entries *──1 personnel
-- personnel 1──* personnel_files (self-reference: replaces_document_id)
-- personnel 1──* promotion_applications *──1 promotion_cycles
-- Standalone: backup_runs, used_magic_tokens, workflow_outbox
